### ISSUE TITLE
ccsm-0.8.12: Segment fault when click any list item

### ISSUE THREAD

**Issue by moontide** [raveit65/ccsm#1]
ccsm will crash if any list item is clicked. For example: click a list item in "General Options -- Display Settings  -- Outputs".

ccsm-0.8.9-1.fc23 does not have this issue.

Command line output:

	$ LANG=en_US.UTF-8 ccsm
	/usr/lib64/python2.7/site-packages/gi/overrides/Gtk.py:50: RuntimeWarning: You have imported the Gtk 2.0 module.  Because Gtk 2.0 was not designed for use with introspection some of the interfaces and API will fail.  As such this is not supported by the pygobject development team and we encourage you to port your app to Gtk 3 or greater. PyGTK is the recomended python module to use with Gtk 2.0
	  warnings.warn(warn_msg, RuntimeWarning)
	/usr/lib/python2.7/site-packages/ccm/Settings.py:25: PyGIWarning: PangoCairo was imported without specifying a version first. Use gi.require_version('PangoCairo', '1.0') before import to ensure that the right version gets loaded.
	  from gi.repository import Pango, PangoCairo
	Loading icons...
	段错误

**Comment by moontide** [comment]
I recorded a video here: https://youtu.be/uk80daX9FYA

**Comment by raveit65** [comment]
Confirmed with fedora 23, for some reason it doesn't happen with f22.
@XRevan86 
i've a stackstace local.

**Comment by raveit65** [comment]
@moontide 
can you please test a fixed build of ccsm?
https://dl.dropboxusercontent.com/u/49862637/Comiz/ccsm-0.8.12.1-2.fc23.noarch.rpm

**Comment by moontide** [comment]
@raveit65: `ccsm-0.8.12.1-2.fc23.noarch.rpm` seems works ok , issue is fixed.
